package DiplomaProject;

public enum PopularManName {
    VIACHESLAV("Viacheslav"),
    MIKHAIL("Mikhail"),
    EUGENIY("Eugeniy"),
    ROMAN("Roman"),
    GRIGORIY("Grigoriy"),
    LEV("Lev"),
    ANDREY("Andrey"),
    ARSENIY("Arseniy"),
    STEPAN("Stepan"),
    VLADISLAV("Vladislav"),
    NIKITA("Nikita"),
    GLEB("Gleb"),
    MARK("Mark"),
    DAVID("David"),
    YAROSLAV("Yaroslav"),
    MATVEY("Matvey"),
    FEDOR("Fedor"),
    NIKOLAY("Nikolay"),
    ALEXEY("Alexey"),
    ALEXANDR("Alexandr"),
    ALEKSANDR("Aleksandr"),
    ALBERT("Albert"),
    ANATOLIY("Anatoliy"),
    ANTON("Anton"),
    ARKADIY("Arkadiy"),
    ARTEM("Artem"),
    ARTEMIY("Artemiy"),
    ARTUR("Artur"),
    ARHIPP("Arhipp"),
    BOGDAN("Bogdan"),
    BORIS("Boris"),
    VADIM("Vadim"),
    VALENTIN("Valentin"),
    VALERIY("Valeriy"),
    VASILIY("Vasiliy"),
    VENIAMIN("Veniamin"),
    VIKTOR("Victor"),
    VITALIY("Vitaliy"),
    VLADIMIR("Vladimir"),
    GENNADIY("Gennadiy"),
    GEORGIY("Georgiy"),
    DANIIL("Daniil"),
    DENIS("Denis"),
    DMITRIY("Dmitriy"),
    EGOR("Egor"),
    IVAN("Ivan"),
    IGOR("Igor"),
    ILYA("Ilya"),
    KIRILL("Kirill"),
    KONSTANTIN("Konstantin"),
    LEONID("Leonid"),
    MAKSIM("Maksim"),
    MAXIM("Maxim"),
    MIROSLAV("Miroslav"),
    MSTISLAV("Mstislav"),
    NAZAR("Nazar"),
    OLEG("Oleg"),
    PAVEL("Pavel"),
    PETR("Petr"),
    PLATON("Platon"),
    POTAP("Potap"),
    PROHOR("Prohor"),
    RODION("Rodion"),
    ROSTISLAV("Rostislav"),
    RUSLAN("Ruslan"),
    SAVELIY("Saveliy"),
    SVYATOSLAV("Svyatoslav"),
    SEMEN("Semen"),
    SERGEY("Sergey"),
    STANISLAV("Stanislav"),
    TARAS("Taras"),
    TIMOFEY("Timofey"),
    TIMUR("Timur"),
    TROFIM("Trofim"),
    FEDOT("Fedot"),
    FILIPP("Filipp"),
    EDUARD("Eduard"),
    ULIAN("Ulian"),
    URIY("Uriy"),
    YAKOV("Yakov");

    private String name;
    PopularManName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
