package DiplomaProject;

public enum PopularWomenName {
    AGAFIA("Agafia"),
    AGRIPPINA("Agrippina"),
    AKULINA("Akulina"),
    ALEVTINA("Alevtina"),
    ALEXANDRA("Alexandra"),
    ALINA("Alina"),
    ALISA("Alisa"),
    ALLA("Alla"),
    ANASTASIIA("Anastasiia"),
    ANGELINA("Angelina"),
    ANZHELA("Anzhela"),
    ANZHELIKA("Anzhelika"),
    ANNA("Anna"),
    ANTONINA("Antonina"),
    ANFISA("Anfisa"),
    VALENTINA("Valentina"),
    VALERIA("Valeria"),
    VARVARA("Varvara"),
    VASILISA("Vasilisa"),
    VERA("Vera"),
    VERONIKA("Veronika"),
    VICTORIA("Victoria"),
    GALINA("Galina"),
    DANA("Dana"),
    DARIA("Daria"),
    EVGENIA("Evgenia"),
    EVDOKIA("Evdokia"),
    EKATERINA("Ekaterina"),
    ELENA("Elena"),
    ELIZAVETA("Elizaveta"),
    ELVIRA("Elvira"),
    ZHANNA("Zhanna"),
    ZINAIDA("Zinaida"),
    ZLATA("Zlata"),
    ZOYA("Zoya"),
    INESSA("Inessa"),
    INNA("Inna"),
    IOANNA("Ioanna"),
    IRINA("Irina"),
    KARINA("Karina"),
    KAROLINA("Karolina"),
    KIRA("Kira"),
    KLAVDIA("Klavdia"),
    KSENIA("Ksenia"),
    LADA("Lada"),
    LARISA("Larisa"),
    LIDIA("Lidia"),
    LILIA("Lilia"),
    LUBOV("Lubov"),
    LUDMILA("Ludmila"),
    MARGARITA("Margarita"),
    MARINA("Marina"),
    MARIA("Maria"),
    MIROSLAVA("Miroslava"),
    NADEZHDA("Nadezhda"),
    NATALIA("Natalia"),
    NINA("Nina"),
    OXANA("Oxana"),
    OLGA("Olga"),
    PAVLINA("Pavlina"),
    POLINA("Polina"),
    RADA("Rada"),
    RAISA("Raisa"),
    REGINA("Regina"),
    RIMMA("Rimma"),
    RUSLANA("Ruslana"),
    SVETLANA("Svetlana"),
    SERAFIMA("Serafima"),
    SNEZHANA("Snezhana"),
    SOFIA("Sofia"),
    TAISIA("Taisia"),
    TAMARA("Tamara"),
    TATIANA("Tatiana"),
    ULIANA("Uliana"),
    URSULA("Ursula"),
    FAINA("Faina"),
    FEODORA("Feodora"),
    YULIA("Yulia"),
    YANA("Yana"),
    YAROSLAVA("Yaroslava");

    private String name;
    PopularWomenName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
